// Code generated by gen_hints; DO NOT EDIT.

package vm

func init() {
	standardInterfaceHints["http.RequestObject"] = Interface{
		Name: "http.RequestObject",
		Fields: map[string]TypeHint{
			"path": stdTypeHint("string"),
			"body": stdTypeHint("string"),
			"formAll": stdTypeHint("object"),
			"method": stdTypeHint("string"),
			"query": stdTypeHint("object"),
			"remoteAddr": stdTypeHint("string"),
			"params": stdTypeHint("object"),
			"headers": stdTypeHint("object"),
			"files": stdTypeHint("object"),
			"multipart": stdTypeHint("bool"),
			"url": stdTypeHint("string"),
			"bodyBytes": TypeHint{Name: "buffer | null", Types: []string{"buffer", "null"}},
			"form": stdTypeHint("object"),
			"contentLength": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["http.UploadedFile"] = Interface{
		Name: "http.UploadedFile",
		Fields: map[string]TypeHint{
			"field": stdTypeHint("string"),
			"filename": stdTypeHint("string"),
			"contentType": stdTypeHint("string"),
			"size": stdTypeHint("number"),
			"bytes": stdTypeHint("buffer"),
			"text": stdTypeHint("string"),
		},
	}

	standardInterfaceHints["http.HttpResponse"] = Interface{
		Name: "http.HttpResponse",
		Fields: map[string]TypeHint{
			"statusText": stdTypeHint("string"),
			"body": stdTypeHint("string"),
			"headers": stdTypeHint("object"),
			"status": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["http.ServerOptions"] = Interface{
		Name: "http.ServerOptions",
		Fields: map[string]TypeHint{
			"port": stdTypeHint("number"),
			"host": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"readTimeoutMs": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"writeTimeoutMs": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"maxBodySize": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
		},
	}

	standardInterfaceHints["http.RequestOptions"] = Interface{
		Name: "http.RequestOptions",
		Fields: map[string]TypeHint{
			"headers": TypeHint{Name: "object | null", Types: []string{"object", "null"}},
			"timeoutMs": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"bytes": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
		},
	}

	standardInterfaceHints["http.FullRequestOptions"] = Interface{
		Name: "http.FullRequestOptions",
		Fields: map[string]TypeHint{
			"method": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"url": stdTypeHint("string"),
			"headers": TypeHint{Name: "object | null", Types: []string{"object", "null"}},
			"body": TypeHint{Name: "any | null", Types: []string{"any", "null"}},
			"timeoutMs": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"bytes": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
		},
	}

	standardInterfaceHints["http.MultipartFile"] = Interface{
		Name: "http.MultipartFile",
		Fields: map[string]TypeHint{
			"field": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"filename": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"contentType": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"path": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"bytes": TypeHint{Name: "buffer | null", Types: []string{"buffer", "null"}},
			"text": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
		},
	}

	standardInterfaceHints["http.MultipartBody"] = Interface{
		Name: "http.MultipartBody",
		Fields: map[string]TypeHint{
			"form": TypeHint{Name: "object | null", Types: []string{"object", "null"}},
			"files": TypeHint{Name: "array:MultipartFile | object | null", Types: []string{"array:MultipartFile", "object", "null"}},
			"multipart": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
		},
	}

	standardInterfaceHints["json.SafeParseResult"] = Interface{
		Name: "json.SafeParseResult",
		Fields: map[string]TypeHint{
			"success": stdTypeHint("bool"),
			"data": TypeHint{Name: "object | null", Types: []string{"object", "null"}},
		},
	}

	standardInterfaceHints["math.Matrix"] = Interface{
		Name: "math.Matrix",
		Fields: map[string]TypeHint{
			"rows": stdTypeHint("number"),
			"cols": stdTypeHint("number"),
			"rawData": stdTypeHint("buffer"),
		},
	}

	standardInterfaceHints["observer.ObserverMemoryStats"] = Interface{
		Name: "observer.ObserverMemoryStats",
		Fields: map[string]TypeHint{
			"totalAlloc": stdTypeHint("number"),
			"heapSys": stdTypeHint("number"),
			"nextGC": stdTypeHint("number"),
			"alloc": stdTypeHint("number"),
			"numGC": stdTypeHint("number"),
			"sys": stdTypeHint("number"),
			"heapAlloc": stdTypeHint("number"),
			"heapObjects": stdTypeHint("number"),
			"pauseTotal": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["observer.ObserverTaskPoolStats"] = Interface{
		Name: "observer.ObserverTaskPoolStats",
		Fields: map[string]TypeHint{
			"active": stdTypeHint("number"),
			"idle": stdTypeHint("number"),
			"limit": stdTypeHint("number"),
			"maxActive": stdTypeHint("number"),
			"maxIdle": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["observer.ObserverTaskStats"] = Interface{
		Name: "observer.ObserverTaskStats",
		Fields: map[string]TypeHint{
			"started": stdTypeHint("number"),
			"active": stdTypeHint("number"),
			"completed": stdTypeHint("number"),
			"failed": stdTypeHint("number"),
			"calls": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["observer.ObserverFunctionCall"] = Interface{
		Name: "observer.ObserverFunctionCall",
		Fields: map[string]TypeHint{
			"name": stdTypeHint("string"),
			"calls": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["observer.ObserverControlStats"] = Interface{
		Name: "observer.ObserverControlStats",
		Fields: map[string]TypeHint{
			"gomaxprocs": stdTypeHint("number"),
			"gcPercent": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["observer.ObserverNamedItem"] = Interface{
		Name: "observer.ObserverNamedItem",
		Fields: map[string]TypeHint{
			"name": stdTypeHint("string"),
		},
	}

	standardInterfaceHints["observer.ObserverEvent"] = Interface{
		Name: "observer.ObserverEvent",
		Fields: map[string]TypeHint{
			"time": stdTypeHint("string"),
			"kind": stdTypeHint("string"),
			"message": stdTypeHint("string"),
			"data": TypeHint{Name: "any | null", Types: []string{"any", "null"}},
		},
	}

	standardInterfaceHints["observer.ObserverMessage"] = Interface{
		Name: "observer.ObserverMessage",
		Fields: map[string]TypeHint{
			"from": stdTypeHint("string"),
			"text": stdTypeHint("string"),
			"data": TypeHint{Name: "any | null", Types: []string{"any", "null"}},
			"time": stdTypeHint("string"),
		},
	}

	standardInterfaceHints["observer.ObserverSnapshot"] = Interface{
		Name: "observer.ObserverSnapshot",
		Fields: map[string]TypeHint{
			"executable": stdTypeHint("string"),
			"cwd": stdTypeHint("string"),
			"controls": stdTypeHint("ObserverControlStats"),
			"stackDepth": stdTypeHint("number"),
			"goarch": stdTypeHint("string"),
			"taskPool": stdTypeHint("ObserverTaskPoolStats"),
			"events": stdTypeHint("array:ObserverEvent"),
			"globalCount": stdTypeHint("number"),
			"uptimeMs": stdTypeHint("number"),
			"pid": stdTypeHint("number"),
			"gomaxprocs": stdTypeHint("number"),
			"frameDepth": stdTypeHint("number"),
			"memory": stdTypeHint("ObserverMemoryStats"),
			"functionCount": stdTypeHint("number"),
			"interfaceCount": stdTypeHint("number"),
			"messages": stdTypeHint("array:ObserverMessage"),
			"functionNames": stdTypeHint("array:string"),
			"classCount": stdTypeHint("number"),
			"classNames": stdTypeHint("array:string"),
			"functionCalls": stdTypeHint("array:ObserverFunctionCall"),
			"commands": stdTypeHint("array:ObserverNamedItem"),
			"goroutines": stdTypeHint("number"),
			"tasks": stdTypeHint("ObserverTaskStats"),
			"exposed": stdTypeHint("array:ObserverNamedItem"),
			"goos": stdTypeHint("string"),
			"globalNames": stdTypeHint("array:string"),
			"status": stdTypeHint("string"),
		},
	}

	standardInterfaceHints["observer.ObserverServer"] = Interface{
		Name: "observer.ObserverServer",
		Fields: map[string]TypeHint{
			"url": stdTypeHint("string"),
			"host": stdTypeHint("string"),
			"port": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["observer.ObserverServerOptions"] = Interface{
		Name: "observer.ObserverServerOptions",
		Fields: map[string]TypeHint{
			"password": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"host": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"port": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
		},
	}

	standardInterfaceHints["process.ProcessOptions"] = Interface{
		Name: "process.ProcessOptions",
		Fields: map[string]TypeHint{
			"cwd": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"stdout": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"stderr": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
		},
	}

	standardInterfaceHints["process.ProcessResult"] = Interface{
		Name: "process.ProcessResult",
		Fields: map[string]TypeHint{
			"stdout": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"stderr": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"success": stdTypeHint("bool"),
			"exitCode": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["runtime.MemoryStats"] = Interface{
		Name: "runtime.MemoryStats",
		Fields: map[string]TypeHint{
			"numGC": stdTypeHint("number"),
			"alloc": stdTypeHint("number"),
			"totalAlloc": stdTypeHint("number"),
			"sys": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["runtime.VMStdlibOptions"] = Interface{
		Name: "runtime.VMStdlibOptions",
		Fields: map[string]TypeHint{
			"json": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"buffer": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"regex": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"http": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"observer": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"desktop": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"runtime": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"array": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"net": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"time": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"object": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"error": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"sync": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"ui": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"path": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"tests": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"tray": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"url": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"app": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"os": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"websocket": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"validate": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"strings": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"fs": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"io": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"process": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"math": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
		},
	}

	standardInterfaceHints["runtime.VMOptions"] = Interface{
		Name: "runtime.VMOptions",
		Fields: map[string]TypeHint{
			"globals": TypeHint{Name: "object | null", Types: []string{"object", "null"}},
			"disableJIT": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"runMainOnLoad": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"isolated": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"allowedStdlib": TypeHint{Name: "VMStdlibOptions | null", Types: []string{"VMStdlibOptions", "null"}},
			"cliArgs": TypeHint{Name: "array | null", Types: []string{"array", "null"}},
		},
	}

	standardInterfaceHints["tray.Bounds"] = Interface{
		Name: "tray.Bounds",
		Fields: map[string]TypeHint{
			"y": stdTypeHint("number"),
			"width": stdTypeHint("number"),
			"height": stdTypeHint("number"),
			"x": stdTypeHint("number"),
		},
	}

	standardInterfaceHints["ui.WebViewOptions"] = Interface{
		Name: "ui.WebViewOptions",
		Fields: map[string]TypeHint{
			"debug": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"hidden": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
			"frameless": TypeHint{Name: "bool | null", Types: []string{"bool", "null"}},
		},
	}

	standardInterfaceHints["validate.SafeParseResult"] = Interface{
		Name: "validate.SafeParseResult",
		TypeParameters: []string{"T"},
		Fields: map[string]TypeHint{
			"success": stdTypeHint("bool"),
			"data": stdTypeHint("T"),
			"error": stdTypeHint("any"),
		},
	}

	standardInterfaceHints["websocket.Message"] = Interface{
		Name: "websocket.Message",
		Fields: map[string]TypeHint{
			"type": stdTypeHint("string"),
			"data": stdTypeHint("any"),
		},
	}

	standardInterfaceHints["websocket.ClientOptions"] = Interface{
		Name: "websocket.ClientOptions",
		Fields: map[string]TypeHint{
			"timeoutMs": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"maxMessageSize": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"headers": TypeHint{Name: "object | null", Types: []string{"object", "null"}},
		},
	}

	standardInterfaceHints["websocket.ServerOptions"] = Interface{
		Name: "websocket.ServerOptions",
		Fields: map[string]TypeHint{
			"maxMessageSize": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"port": stdTypeHint("number"),
			"host": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"path": TypeHint{Name: "string | null", Types: []string{"string", "null"}},
			"readTimeoutMs": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
			"writeTimeoutMs": TypeHint{Name: "number | null", Types: []string{"number", "null"}},
		},
	}

	standardInterfaceHints["websocket.CloseEvent"] = Interface{
		Name: "websocket.CloseEvent",
		Fields: map[string]TypeHint{
			"wasClean": stdTypeHint("bool"),
			"code": stdTypeHint("number"),
			"reason": stdTypeHint("string"),
		},
	}

}
