// gen_hints reads .tiny stub files and generates vm/types_generated.go
// with standardInterfaceHints entries.
//
// Usage:
//
//	go run ./cmd/gen_hints
//
// Or via go generate:
//
//	go generate ./...
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"language.com/src/vm"
)

func main() {
	// Find the correct paths depending on where the script is executed
	var stubDir string
	var outPath string

	candidates := []string{
		".",          // run from src
		"..",         // run from src/vm or src/cmd/gen_hints
		"src",        // run from repo root
		"../src",     // run from cmd/gen_hints
	}

	found := false
	for _, c := range candidates {
		dir := filepath.Join(c, "lsp_stubs")
		if info, err := os.Stat(dir); err == nil && info.IsDir() {
			stubDir = dir
			outPath = filepath.Join(c, "vm", "types_generated.go")
			found = true
			break
		}
	}

	if !found {
		fmt.Fprintf(os.Stderr, "error: could not locate 'lsp_stubs' directory. Make sure you run from the repo root, src/, or src/vm/.\n")
		os.Exit(1)
	}

	files, err := filepath.Glob(filepath.Join(stubDir, "*.tiny"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "error globbing stubs: %v\n", err)
		os.Exit(1)
	}

	type entry struct {
		key   string
		iface vm.Interface
	}
	var entries []entry

	for _, file := range files {
		module := strings.TrimSuffix(filepath.Base(file), ".tiny")

		src, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error reading %s: %v\n", file, err)
			os.Exit(1)
		}

		lexer := vm.NewLexer(string(src), file)
		parser := vm.NewParser(lexer)
		prog := parser.ParseProgramTolerant()

		for _, stmt := range prog.Statements {
			ifaceStmt, ok := interfaceStmtFromStmt(stmt)
			if !ok {
				continue
			}
			key := module + "." + ifaceStmt.Name
			fields := map[string]vm.TypeHint{}
			for fname, ftype := range ifaceStmt.Fields {
				fields[fname] = ftype
			}
			entries = append(entries, entry{
				key: key,
				iface: vm.Interface{
					Name:           key,
					TypeParameters: ifaceStmt.TypeParameters,
					Extends:        ifaceStmt.Extends,
					Fields:         fields,
				},
			})
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by gen_hints; DO NOT EDIT.\n\n")
	b.WriteString("package vm\n\n")
	b.WriteString("func init() {\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\tstandardInterfaceHints[%q] = Interface{\n", e.key))
		b.WriteString(fmt.Sprintf("\t\tName: %q,\n", e.key))
		if len(e.iface.TypeParameters) > 0 {
			params := make([]string, len(e.iface.TypeParameters))
			for i, p := range e.iface.TypeParameters {
				params[i] = fmt.Sprintf("%q", p)
			}
			b.WriteString(fmt.Sprintf("\t\tTypeParameters: []string{%s},\n", strings.Join(params, ", ")))
		}
		if len(e.iface.Extends) > 0 {
			extends := make([]string, len(e.iface.Extends))
			for i, p := range e.iface.Extends {
				extends[i] = fmt.Sprintf("%q", p)
			}
			b.WriteString(fmt.Sprintf("\t\tExtends: []string{%s},\n", strings.Join(extends, ", ")))
		}
		b.WriteString("\t\tFields: map[string]TypeHint{\n")
		for fname, ftype := range e.iface.Fields {
			b.WriteString(fmt.Sprintf("\t\t\t%q: %s,\n", fname, typeHintString(ftype)))
		}
		b.WriteString("\t\t},\n")
		b.WriteString("\t}\n\n")
	}
	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating output dir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("generated %s (%d interfaces)\n", outPath, len(entries))
}

func interfaceStmtFromStmt(stmt vm.Stmt) (vm.InterfaceStmt, bool) {
	if iface, ok := stmt.(vm.InterfaceStmt); ok {
		return iface, true
	}
	if exported, ok := stmt.(vm.ExportStmt); ok {
		if iface, ok := exported.Inner.(vm.InterfaceStmt); ok {
			return iface, true
		}
	}
	return vm.InterfaceStmt{}, false
}

func typeHintString(h vm.TypeHint) string {
	if len(h.Fields) > 0 {
		parts := []string{fmt.Sprintf("Name: %q", h.Name)}
		fieldParts := make([]string, 0, len(h.Fields))
		for name, field := range h.Fields {
			fieldParts = append(fieldParts, fmt.Sprintf("%q: %s", name, typeHintString(field)))
		}
		sort.Strings(fieldParts)
		parts = append(parts, "Fields: map[string]TypeHint{"+strings.Join(fieldParts, ", ")+"}")
		return "TypeHint{" + strings.Join(parts, ", ") + "}"
	}
	if len(h.Types) > 0 {
		parts := make([]string, len(h.Types))
		for i, t := range h.Types {
			parts[i] = fmt.Sprintf("%q", t)
		}
		return fmt.Sprintf("TypeHint{Name: %q, Types: []string{%s}}", h.Name, strings.Join(parts, ", "))
	}
	return fmt.Sprintf("stdTypeHint(%q)", h.Name)
}
